--Этот скрипт будет всегда с открытом кодом
getgenv().Config = {
    Holdok = false
}
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))()
local Window = Library:NewWindow("Holdok gay")
local MainSection = Window:NewSection("Player Scripts")
MainSection:CreateButton("Fly", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XNEOFF/FlyGuiV3/main/FlyGuiV3.txt"))()
end)
MainSection:CreateButton("Inf Eld", function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'),true))()
end)
MainSection:CreateButton("Rspy", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/RS/main/SimpleSpyMobile"))()
end)
MainSection:CreateButton("Keyboard", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
local MainSection = Window:NewSection("More Dex")
MainSection:CreateButton("Dark Dex", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
MainSection:CreateButton("Dex Fix", function()
loadstring(game:HttpGet("https://github.com/Hosvile/DEX-Explorer/releases/latest/download/main.lua", true))()
end)
local MainSection = Window:NewSection("Games")
MainSection:CreateButton("Car Dealership Tycoon", function()
    loadstring(game:HttpGet("https://ahsrua.com"))()
end)
MainSection:CreateButton("Doors And More Games", function()
    loadstring(game:HttpGet('https://rawscripts.net/raw/DOORS-FFJ-Hub-11365'))()
end)
