--Этот скрипт будет всегда с открытом кодом

local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wizard"))()
local Window = Library:NewWindow("Holdok gay")
local MainSection = Window:NewSection("Player Scripts")
MainSection:CreateButton("Fly", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/XNEOFF/FlyGuiV3/main/FlyGuiV3.txt"))()
end)
MainSection:CreateButton("Inf Eld", function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'),true))()
end)
MainSection:CreateButton("Keyboard", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt", true))()
end)
MainSection:CreateButton("Auto clicker", function()
getgenv().key = "Hostile"
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Hosvile/The-telligence/main/MC%20KSystem%202"))()
end)
MainSection:CreateButton("Hub Scripts)", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/artemy133563/Utilities/main/WyvernV2",true))()
end)
local MainSection = Window:NewSection("Rspy")
MainSection:CreateButton("hydroxide Fix", function()
   local owner = "Hosvile"
    local branch = "revision"
     local function webImport(file)
      return loadstring(game:HttpGetAsync(("https://raw.githubusercontent.com/%s/MC-Hydroxide/%s/%s.lua"):format(owner, branch, file)), file .. '.lua')()
end
webImport("init")
webImport("ui/main")
end)
MainSection:CreateButton("Rspy Fix", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/REDzHUB/RS/main/SimpleSpyMobile"))()
end)
local MainSection = Window:NewSection("Dex")
MainSection:CreateButton("Dark Dex", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
MainSection:CreateButton("Dex Fix", function()
loadstring(game:HttpGet("https://github.com/Hosvile/DEX-Explorer/releases/latest/download/main.lua", true))()
end)
local MainSection = Window:NewSection("Games")
MainSection:CreateButton("Car Dealership Tycoon", function()
    loadstring(game:HttpGet("https://ahsrua.com"))()
end)
MainSection:CreateButton("Doors And More Games", function()
    loadstring(game:HttpGet('https://rawscripts.net/raw/DOORS-FFJ-Hub-11365'))()
end)
